config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  devise_for :users

  delete '/assets/:id/:asset_data_id' , to: 'assets#destroy_asset_data'

  resources :users  , except: [ :create , :new ] do
    collection do
      get 'index'
    end
  end

  resources :sub_categories
  
  resources :categories do
    member do
      get 'sub_categories'
    end
  end
  
  resources :descriptors
  
  resources :assets 

  resources :asset_data
  
  match 'offers/choose_assets' => 'offers#choose_assets', :via => :post

  resources :offers do
    member do
      get 'show_received'
      put 'accept'
      put 'reject'
    end

    collection do
      get 'received_offers'
    end
  end

  

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base

  belongs_to :category
  has_many :asset

  validates :name, :presence => true
  validates :category , :presence => true

  before_save :default_values

  def default_values
  	self.active = true if active.nil?
  end

end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]
  
  load_and_authorize_resource

  respond_to :html , :json , :xml

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)
    if @sub_category.save
       respond_with @sub_category, notice: 'Sub category was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    if @sub_category.update(sub_category_params)
      respond_with @sub_category, notice: 'Sub category was successfully updated.' 
    else
      render :edit 
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    @sub_categories = SubCategory.all
    redirect_to sub_categories_url , notice: 'Sub category was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:name, :active, :category_id)
    end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<br/>
<div class="container">
  <div class="row">
    <div class= "col-lg-6 col-lg-offset-3">
      <div class="well bs-component">
        <%= form_for(@sub_category , html: { class: "form-horizontal" } ) do |f| %>

        <% if @sub_category.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@sub_category.errors.count, "error") %> prohibited this Sub category from being saved:
            </h2>

            <ul>
              <% @sub_category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <fieldset>
          <legend>Sub Category</legend>

          <div class="form-group">
            <label for="name" class="col-lg-2 control-label">Name</label>

            <div class="col-lg-10">
              <%= f.text_field :name, class: 'form-control' , placeholder: 'Name' , autofocus: true %>
            </div>
          </div>

          <div class="form-group">
              <label for="category_id" class="col-lg-2 control-label">Category</label>
              
              <div class="col-lg-5">
                <%= f.collection_select :category_id ,  Category.where(active: true) , :id , 
                    :name ,{}, 
                    { :class => "selectpicker", "data-style" => "btn-warning", 
                      "data-live-search" => "true" }  %>
              </div>
          </div>

          <div class="form-group">
            <div class="checkbox">
              <div class="col-lg-4 col-lg-offset-2 ">
                <%= f.check_box :active %> Active
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="col-lg-1 col-lg-offset-4">
              <% if @sub_category.id.nil? %>
                <%= f.submit "Create", class: "btn btn-success" %>  
              <% else %>
                <%= f.submit "Update", class: "btn btn-success" %>  
              <% end %>
            </div>

            <div class="col-lg-5 col-lg-offset-2">
              <%= button_to "Cancel", sub_categories_path , class: "btn btn-danger" %>
            </div>
          </div>

        </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sub_categories/edit.html.erb
<%= render 'form' %>

app/views/sub_categories/index.html.erb
<br/>
<div class="container">
 <table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.name %></td>
        <td><%= sub_category.active %></td>
        <td><%= sub_category.category.name %></td>
        <td><%= link_to icon('show'), sub_category %></td>
        <td><%= link_to icon('edit'), edit_sub_category_path(sub_category) %></td>
        <td><%= link_to icon('remove'), sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-group">
    <div class="col-lg-1">
       <%= link_to 'New Sub category', new_sub_category_path, class: "btn btn-success" %>
    </div>
  </div>

</div>

app/views/sub_categories/new.html.erb
<%= render 'form' %>

app/views/sub_categories/show.html.erb
<br/>
<div class="container">
 
 <div class="well bs-component col-lg-4 col-lg-offset-4">

 <fieldset>
   <legend>Sub Category</legend>

  <div class="form-group">
       <label for="name" class="control-label">Name :</label>
       <label class="control-label"><%= @sub_category.name %></label>
  </div>

  <div class="form-group">
       <label for="name" class="control-label">Category :</label>
       <label class="control-label"><%= Category.find(@sub_category.category_id).name %></label>
  </div>

  <div class="form-group">
       <label for="name" class="control-label">Active :</label>
       <label class="control-label"><%= @sub_category.active %></label>
  </div>

  <div class="form-group">
    <%= link_to 'Edit', edit_sub_category_path(@sub_category), class: "btn btn-success" %>
    <%= link_to 'Back', sub_categories_path, class: "btn btn-danger" %>
  </div>

  </fieldset>

 </div>
</div>