config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  devise_for :users

  delete '/assets/:id/:asset_data_id' , to: 'assets#destroy_asset_data'

  resources :users  , except: [ :create , :new ] do
    collection do
      get 'index'
    end
  end

  resources :sub_categories
  
  resources :categories do
    member do
      get 'sub_categories'
    end
  end
  
  resources :descriptors
  
  resources :assets 

  resources :asset_data
  
  match 'offers/choose_assets' => 'offers#choose_assets', :via => :post

  resources :offers do
    member do
      get 'show_received'
      put 'accept'
      put 'reject'
    end

    collection do
      get 'received_offers'
    end
  end

  

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :status
  belongs_to :from , class_name: 'User'
  belongs_to :to , class_name: 'User'
  has_many :offer_asset , :dependent => :destroy
  has_many :asset , :through => :offer_asset

  validates :from , :presence => true
  validates :to , :presence => true
  validates :status , :presence => true

  state_machine :state, :initial => :new do

    event :edit do
      transition [:new] => :pending
      transition [:pending] => :updated
    end

    event :seen do
      transition [:updated] => :pending
    end

    event :accept do
      transition [:pending, :updated] => :accepted
    end

    event :reject do
      transition [:pending, :updated] => :rejected
    end

    event :cancel do
      transition [:new] => :cancelled
    end

  end

  def given_assets
  	asset.where('assets.user_id' => from.id)
  end

  def received_assets
  	asset.where('assets.user_id' => to.id)
  end

  def from_assets
  	Asset.where(user_id: from.id)
  end

  def to_assets
  	Asset.where(user_id: to.id)
  end

  def choosed_assets
  end

  def choosed_assets=(assets)
    asset.destroy_all
    assets.each do |asset_id|
      OfferAsset.create(offer_id: id, asset_id: asset_id)
    end
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_offer, only: [:show, :edit, :update, :destroy,
                                   :show_received, :accept, :reject]

  before_action :choose_assets_init, only: [:choose_assets]

  load_and_authorize_resource
  
  respond_to :html , :json ,:xml

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.where(from_id: current_user.id)
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/1
  # GET /offers/1.json
  def show_received
  end

  # GET /offers/new
  def new
    @offer = Offer.new
    @users = User.users_list
  end

  # GET /offers/1/edit
  def edit
    render :choose_assets
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params.merge( from_id: current_user.id , status_id: 1 ))
    #if @offer.save
      render :choose_assets , :params => params
    #else        
     # render :new
    #end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    if @offer.update(offer_params)
      respond_with @asset, notice: 'Asset was successfully updated.'
    else        
      render :edit
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    redirect_to offers_url, notice: 'Asset was successfully destroyed.'
  end

  def choose_assets

    @offer.choosed_assets = offer_params[:choosed_assets]
    @offer.edit # state machine event
    
    if offer_params[:origin] == 'received_offers' 
      redirect_to action: "received_offers"
    else
      redirect_to action: "index"
    end

  end

  def received_offers
    @offers = Offer.where(to_id: current_user.id)
  end

  def accept
    @offer.accept
    redirect_to action: "received_offers"
  end

  def reject
    @offer.reject
    redirect_to action: "received_offers"
  end

  private
    
    def choose_assets_init
      if offer_params[:id].blank?
        @offer = Offer.new( to_id: offer_params[:to_id], from_id: current_user.id, status_id: 1 )
        @offer.save
      else
        @offer = Offer.find(offer_params[:id])
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_offer
        @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params      
      params.require(:offer).permit(:to_id, :id, :origin, choosed_assets:[] )
    end
end

app/helpers/offers_helper.rb
module OffersHelper

  def checked
  	@offer.asset.pluck(:id).include?(@asset.id) ? "checked" : ""
  end

  def render_asset_info(asset)
  	@asset = asset
  	render :partial => 'assets/asset_info'
  end

  def get_caption()
  	 if @offer.state == "new"
  	 	"Create"
  	 else
  	 	"Update"
  	 end
  end

  def contact_email(offer, user)

    if offer.state == "accepted"
        user.contact_email.blank? ? user.email : user.contact_email
    else
        "Hidden until the offer is accepted"
     end
  end

end

app/views/offers/_assets.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Category</th>
      <th>Descriptors</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <% assets.each do |asset| %>
    <%= render 'assets_row' , :f => f , :att_name => att_name  , :asset => asset %>
  <% end %>
</table>

app/views/offers/_assets_row.html.erb
<tr>
 <%= render_asset_info(asset) %>
 <td>
  <%= f.check_box(att_name , { :multiple => true , :checked => checked }, asset.id, nil ) %>
 </td>
</tr>

app/views/offers/_choose_assets_form.html.erb
<div class="container">
<%= form_for(@offer , :url => offers_choose_assets_path , html: { class: "form-horizontal" }, :method => :POST ) do |f| %>
  
  <% 
     origin = params[:origin]
     from_assets = ( origin == 'received_offers' ? @offer.to_assets : @offer.from_assets ) 
     to_assets = ( origin == 'received_offers' ? @offer.from_assets : @offer.to_assets ) %>

     <%= f.hidden_field :to_id, :value => @offer.to_id %>
     <%= f.hidden_field :id, :value => @offer.id %>

    <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="5" style="text-align:center; vertical-align:middle;">Give</th>
        <th colspan="5" style="text-align:center; vertical-align:middle;">Receive</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td colspan="5">
            <%= render 'assets' , :f => f , :assets => from_assets , :att_name => "choosed_assets" %>
        </td>

        <td colspan="5" style="border-left: 1px solid black">
            <%= render 'assets' , :f => f , :assets => to_assets , :att_name => "choosed_assets" %>
        </td>
      </tr>
    </tbody>

  </table>

  <%= f.hidden_field :origin, :value => origin %>

  <div class="form-group">
    <div class="col-lg-1 col-lg-offset-5">
       <%= f.submit get_caption(), class: "btn btn-success" %>  
    </div>
  
    <div class="col-lg-1 col-lg-offset-1">
       <%= link_to "Cancel", cancel_path , class: "btn btn-danger" %>
    </div>

  </div>

<% end %>
  </div>

app/views/offers/_form.html.erb
<div class="container">
  <div class="row">
    <div class= "col-lg-4 col-lg-offset-4">
      <div class="well bs-component">
        <%= form_for(@offer) do |f| %>
          <div class="form-group">
            <% if @offer.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>
                <ul>
                  <% @offer.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </div>

          <fieldset>

            <legend>Make Offer To</legend>

            <div class="form-group">

              <div class="col-lg-2 col-lg-offset-1">
                <%= f.select :to_id , options_for_select(@users),
                    { :include_blank => "Please select..." },
                    { :class => "selectpicker", "data-style" => "btn-warning", 
                      "data-live-search" => "true" } %>
              </div>
            </div>

            <br/> <br/>

            <div class="form-group">
              <div class="col-lg-1 col-lg-offset-4">
                <%= f.submit "Next", class: "btn btn-success" %>  
              </div>
            </div>

          </fieldset>

      <% end %>
    </div>
  </div>
 </div>
</div>

app/views/offers/_offers_list.html.erb
<% user_text = ( origin == 'received_offers' ? 'From' : 'To' ) %>

<div class="container">
  <table class="table table-striped">
  
  <thead>
    <tr>
      <th>ID</th>
      <!-- <th> <%= user_text %> </th> -->
      <th>Status</th>
      <th>Creation Date</th>
      <th>Contact Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  </tbody>
    <% @offers.each do |offer| 
    	user_name = ( origin == 'received_offers' ? offer.from.full_name : offer.to.full_name )
    	show_link = ( origin == 'received_offers' ? show_received_offer_path(offer) : offer_path(offer) )
      user = ( origin == 'received_offers' ? offer.from : offer.to )
    %>
      <tr>
        <td><%= offer.id %></td>
        <!-- <td><%= user_name %></td> -->
        <td><%= offer.state %></td>
        <td><%= offer.created_at %></td>
        <td><%= contact_email( offer, user ) %></td>

        <td> <%= link_to icon("show"), show_link %> </td>
    
        <% if origin == 'my_offers' %>
          <td> <%= link_to icon("edit"), edit_offer_path(offer, origin: origin ) %> </td>
          <td><%= link_to icon("remove"), offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>

  </table>

  <br>

  <% if origin == 'my_offers' %>
    <div class="form-group">
      <div class="col-lg-1">
        <%= link_to 'New Offer', new_offer_path, class: "btn btn-success" %>
      </div>
    </div>
  <% end %>

</div>

app/views/offers/_show_offer_row.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Category</th>
      <th>Descriptors</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% assets.each do |asset| %>
      <tr>
        <%= render_asset_info(asset) %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/offers/choose_assets.html.erb
<% if params['origin'] == 'received_offers' %>
  <% cancel_path =  received_offers_offers_path %>
<% else %>
  <% cancel_path = offers_path %>
<% end %>



<%= render 'choose_assets_form', cancel_path: cancel_path %>

app/views/offers/edit.html.erb
<%= render 'form' %>

app/views/offers/index.html.erb
<%= render 'offers_list' , :origin => 'my_offers' %>

app/views/offers/new.html.erb
<%= render 'form' %>

app/views/offers/received_offers.html.erb
<%= render 'offers_list' , :origin => 'received_offers' %>

app/views/offers/show.html.erb
<div class="container">

<table class="table table-striped">
 <thead>
    <tr>
      <th colspan="4" style="text-align:center; vertical-align:middle;">Give</th>
      <th colspan="4" style="text-align:center; vertical-align:middle;">Receive</th>
    </tr>
  </thead>

  <tbody>
    
    <tr>
      <td colspan="4">
        <%= render 'show_offer_row' , :assets => @offer.given_assets %>
      </td>

      <td colspan="4" style="border-left: 1px solid black">
        <%= render 'show_offer_row' , :assets => @offer.received_assets %>
      </td>
    </tr>

  </tbody>
</table>


 <div class="form-group">
    <div class="col-lg-1">
       <%= link_to 'Edit', edit_offer_path(@offer), class: "btn btn-success" %>
    </div>

    <div class="col-lg-1 ">
       <%= link_to 'Back', offers_path, class: "btn btn-danger" %>
    </div>
 </div>
 
</div>

app/views/offers/show_received.html.erb
<div class="container">

<table class="table table-striped">
 <thead>
    <tr>
      <th colspan="4" style="text-align:center; vertical-align:middle;">Give</th>
      <th colspan="4" style="text-align:center; vertical-align:middle;">Receive</th>
    </tr>
  </thead>

  <tbody>
    
    <tr>
      <td colspan="4">
        <%= render 'show_offer_row' , :assets => @offer.received_assets %>
      </td>

      <td colspan="4" style="border-left: 1px solid black">
        <%= render 'show_offer_row' , :assets => @offer.given_assets %>
      </td>
    </tr>

  </tbody>
 </table>

<div class="form-group">
    <div class="col-lg-1">
      <%= form_for(@offer , :url => accept_offer_path(@offer) , :method => :PUT ) do |f| %>
        <%= f.submit 'Accept', class: "btn btn-success" %>
      <% end %> 
    </div>

    <div class="col-lg-1 ">
      <%= form_for(@offer , :url => reject_offer_path(@offer) , :method => :PUT ) do |f| %>
        <%= f.submit 'Reject', class: "btn btn-danger" %>
      <% end %>
    </div>
 </div>

</div>