config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  devise_for :users

  delete '/assets/:id/:asset_data_id' , to: 'assets#destroy_asset_data'

  resources :users  , except: [ :create , :new ] do
    collection do
      get 'index'
    end
  end

  resources :sub_categories
  
  resources :categories do
    member do
      get 'sub_categories'
    end
  end
  
  resources :descriptors
  
  resources :assets 

  resources :asset_data
  
  match 'offers/choose_assets' => 'offers#choose_assets', :via => :post

  resources :offers do
    member do
      get 'show_received'
      put 'accept'
      put 'reject'
    end

    collection do
      get 'received_offers'
    end
  end

  

end

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer navbar navbar-bottom" style="border-top: 5px solid #c52d2f">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                    &copy; 2016  All Rights Reserved.
            </div>
            <div class="col-sm-6">
                <ul class="pull-right">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Faq</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer><!--/#footer-->

app/views/layouts/_header.html.erb
<%= javascript_include_tag('asset_form.js') %>
<header id="header" class="">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="banner" style="">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="index.html"><img src="assets/images/logo.png" alt="logo"></a>
            </div>
        
            <div class="collapse navbar-collapse  navbar-right ">
                <ul class="nav navbar-nav">
                    <li class=""><%= link_to 'Home', root_path %></li>
                    
                    <% if !signed_in? %>
                      <li><%= link_to 'Login', new_user_session_path %></li>
                      <li><%= link_to 'Register', new_user_registration_path %></li>
                    <% else %>
                      <li class="dropdown">
                         <%= link_to 'Offers', offers_path %> 
                          <ul class="dropdown-menu">
                              <li><%= link_to 'My Offers', offers_path %></li>
                              <li><%= link_to 'Received Offers', received_offers_offers_path %></li>
                          </ul>
                      </li>
                      <li><%= link_to 'My Assets', assets_path %></li> 
                      <li><%= link_to 'Profile',  edit_user_path(current_user) %></li>

                      <% if current_user.is_admin? %>
                        <li><%= link_to 'Categories', categories_path %></li> 
                        <li><%= link_to 'Sub Categories',  sub_categories_path %>
                        <li><%= link_to 'Descriptors', descriptors_path %></li> 
                      <% end %>

                      <li><%= link_to 'Log Out', destroy_user_session_path %></li> 
                    <% end %>
                </ul>
            </div>
        </div><!--/.container-->
    </nav><!--/nav-->
</header><!--/header-->

app/views/layouts/_sidebar.html.erb
 <!--sidebar start-->
<aside>
  <div id="sidebar"  class="nav-collapse ">
    <!-- sidebar menu start-->
    <ul class="sidebar-menu">                
      <li class="active">
        <a class="" href="index.html">
          <i class="icon_house_alt"></i>
            <span>Dashboard</span>
        </a>
      </li>

      <li class="sub-menu">
        <a href="javascript:;" class="">
          <i class="icon_document_alt"></i>
            <span>Forms</span>
            <span class="menu-arrow arrow_carrot-right"></span>
        </a>

        <ul class="sub">
          <li><a class="" href="form_component.html">Form Elements</a></li>                          
          <li><a class="" href="form_validation.html">Form Validation</a></li>
        </ul>
      </li>       
    </ul>
           <!-- sidebar menu end-->
  </div>
</aside>
      <!--sidebar end-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>USS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render "layouts/header" %>
  <div id = "wrap"><%= yield %></div>
  <%= render "layouts/footer" %>
  
</body>

</html>